
baseURL = "https://plugins.gethelix.co/"
languageCode = "en-us"
title = "Helix Plugin Center"
theme = "helix"
paginate = 14

[params]
	helixURL = "https://gethelix.co/"
	repoURL = "https://github.com/nebulouscloud/helix-plugins/"
	commandPrefix = "/"

[permalinks]
	plugins = "/:title/"
