
name = "Helix"
license = "MIT"
description = ""
homepage = "https://plugins.gethelix.co/"
tags = []
features = []
min_version = "0.41"

[author]
	name = "Igor Radovanovic"
	homepage = "https://igor.radovanovic.ca"
